image: atlassian/default-image:3

pipelines:
  custom:
    test-decrypt-in-container:
      - step:
          name: Test decryption of a vault encrypted secret in a container
          image:
            name: owsus/ansible-vanilla
          script:
            # test encrypting a string to see if vault is working
            - ansible-vault -vvvvv encrypt_string foo
            # decrypt a previously encrypted secret
            - ansible-vault -vvvvv decrypt foo_file.enc
