# vanilla ansible image
FROM ubuntu:22.04

USER root

WORKDIR /root

RUN apt-get update && apt-get -y install \
  python3 \
  python3-pip
  
RUN pip install ansible

COPY . .

RUN chmod 0700 vault_pass_from_env.sh

ENTRYPOINT ["/bin/bash"]
